
// This page is the home page
import Head from 'next/head';
import Link from 'next/link';
import styles from '@/styles/Home.module.css';
import MessageBox from '@/components/MessageBox';
import { useState } from "react";
import Container from '@/components/Container';
import Button from "../components/Button";
import Title from '@/components/Title';
import Text from '@/components/Text';
import Intro from '@/components/Intro';
import TypeIt from 'typeit-react';


export default function Conclusion() {
  return (
    <>
      <Head>
        <title>D-TEYE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Intro>
          <Title text="BONNE BACCHANIGHT" />
          <img className='w-2/12 mx-auto' src="/d-teye.png" alt="d-teye image" />

          <div className='w-full bg-primary bg-opacity-20 p-4 rounded-md border-2 border-primary z-50'>
        <TypeIt options={{
          strings: ["Vous aurez certainement quelques problèmes si vous peignez sur les toiles présentées au musée des Beaux Arts… "," ","","Mais il y a un endroit où vous pouvez transformer les tableaux sans aucun risque de poursuite judiciaire : votre imagination. Dans vos pensées, tout devient possible."," ","", "J'espère que ce virus sera contagieux ;)","", "Belle BACCHANIGHT."],
          speed: 10,
          waitUntilVisible: true,
        }}className ="text-primary mb-4">
        </TypeIt>
        </div>
        <div className='w-full flex justify-center'>
        <Link href="/credits"><Button text="crédits"/></Link>

        </div>
        </Intro>
        </Container>
    </>
  )
}
