import Head from 'next/head'
import Container from "@/components/Container";
import Link from 'next/link'
import React from 'react';
import TypeIt from 'typeit-react';
import MessageBox from '@/components/MessageBox';
import Title from '@/components/Title';
import Intro from '@/components/Intro';
import Button from "../components/Button";
import Text from '@/components/Text';

export default function Home() {
  return (
  <>
  <Head>
    <title>Credits</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <Container>
    <Intro>
      <Title text="Credits"/>
      <img className='w-1/12 mx-auto' src="/d-teye.png" alt="full-folder" />
      <div className='w-full flex h-full flex-col justify-evenly text-primary text-center '>
        <div className='mb-10'>
          <h2 className='text-xl'><Text text="COLLECTIF ALLELA:"/></h2>
          <p>André, François, Thomas, Paul et Samuel</p>
        </div>
        <div className='flex-col flex gap-y-4 text-primary border-y-2 py-4   border-primary/50'>
          <span className='text-lg'>William Bouguereau:</span>
          <span className='opacity-50'>Le Jour des morts, 1859</span>
          <hr className='w-1/6 mx-auto border-primary' ></hr>
          <span className='text-lg'>John-Lewis Brown:</span>
          <span className='px-10 opacity-50'>Bataille du 17 juin 1815 (Waterloo), 1869</span>
        </div>
        
      </div>
      
      <div className='w-full flex justify-center items-center'>
        <Link href="https://allela-ed132b.webflow.io/home"><Button text="Allela"/></Link>
      </div>
    </Intro>
    <div className='bottom-0 w-full bg-primary absolute flex justify-center p-2'>
        <img className='h-14' src="./logo_bacchanight.png"></img>
  </div>
  </Container>
  </>
  )
}
