import Head from 'next/head'
import Container from "@/components/Container";
import Link from 'next/link'
import React from 'react';
import TypeIt from 'typeit-react';
import MessageBox from '@/components/MessageBox';
import Title from '@/components/Title';
import Intro from '@/components/Intro';
import Button from "../components/Button";
import Text from '@/components/Text';

export default function Home() {
  return (
    <>
      <Head>
        <title>Credits</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
              <Intro>
              <Title text="Credits" />
              <div className='w-full h-40 flex flex-col justify-evenly text-primary text-center '>
                <div className='mb-10'>
                  <h2 className='text-2xl'><Text text="COLLECTIF ALLELA:"/></h2>
                </div>
                <div >
                <TypeIt className='text-2xl' options={{
                  strings: ["ANDRE","FRANCOIS","SAMUEL","PAUL","THOMAS"],
                  speed: 2,
                  waitUntilVisible: true,
                  startDelay: 2000,
                }}></TypeIt>      
              </div>
                                  
              </div>
              <img className='w-4/12 mx-auto' src="/d-teye.png" alt="full-folder" />

              <div className='w-full flex justify-between'>
              <Link href="https://allela-ed132b.webflow.io/home"><Button text="Voir plus"/></Link>
              <Link href="/index"><Button text="récommencer"/></Link>

              </div>
              </Intro>
              </Container>
    </>
  )
}
