
// This page is the home page
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Title from '../components/Title'



export default function Download() {
  return (
    <>
      <Head>
        <title>Download</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex h-screen justify-center items-center'>
        <div className=''>
          <Title text="OUVRIR LE DOSSIER CORROMPU"/>
          <Link href="/paints" className='text-white'>
          <Image
            src="/../public/File_Img.png"
            alt="Picture of a file"
            width={100}
            height={100}
            className="m-auto"
          />
          </Link>
        </div>

      </main>
    </>
  )
}
