
// This page is the home page
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Paint from '@/components/Paint'
import { useState } from "react"
import Score from '@/components/Score'

export default function Game1() {
  const [score, setScore]= useState(0);

  function increaseScore(){
  // Add point to score
    setScore(score + 1);
  };
  return (
    <>
      <Head>
        <title>Game 1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='relative'>
      <Paint itemClick={increaseScore} class="max-w-none " src="/jour_des_morts.jpg"/>
      <Score score={score}/>
      </div>

    </>
  )
}
