
// This page is the home page
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>D-TEYE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1 className='text-primary font-bold'>Jeu 2</h1>
        </div>
        <Link href="/conclusion" className='text-white'>
          Aller à la conclusion
        </Link>
      </main>
    </>
  )
}
