
// This page is the home page
import Head from 'next/head'
import Image from 'next/image'
import Container from "@/components/Container"
import { useState } from "react";
import Button from "../components/Button"
import Link from 'next/link'
import MessageBox from '@/components/MessageBox';
import Title from '@/components/Title';
import Intro from '@/components/Intro';


export default function Home(){
  
  const [slide, setSlide] = useState(0);
  
  const handleNext = () => {
    setSlide(slide + 1)
  }
  <Head>
  <title>D-TEYE</title>
  <meta name="description" content="Generated by create next app" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="icon" href="/favicon.ico" />
  </Head>
  
  switch (slide) {
    case 1:
    return (
      <Container>
      <Intro>
      <Title text="DESINFORMATION" />
      <MessageBox text="Les organisateurs m’accusent de désinformation historique car je me suis permis, à dessein, de rajouter quelques éléments sur certains tableaux..."/>
      <div className='w-full flex justify-end'>
      <Button id={slide} text="SUIVANT" onClick={handleNext}  />
      </div>
      </Intro>
      </Container>
      )
      case 2:
      return (
        <Container>
        <Intro>
        <Title text="LE SENS DU DETAIL" />
        <MessageBox text="Aurez vous l’oeil assez aiguisé pour identifier les différences que j’ai dissimulées dans les versions numériques des peintures"/>
        <div className='w-full flex justify-end'>
        <Link href="/paints"><Button text="suivant"/></Link>
        </div>
        </Intro>
        </Container>
        
        )
        default:
        return (
          <Container>
          <Intro>
          <Title text="PROGRAMME MALVEILLANT" />
          <MessageBox text="Bonjour. Je suis D-tEye:  le virus informatique qui sévit pendant cette bacchanight..."/>
          <div className='w-full flex justify-end'>
          <Button id={slide} text="SUIVANT" onClick={handleNext}  />
          </div>
          </Intro>
          </Container>
          
          )
        }
        
        
      }
      