
// This page is the home page
import Head from 'next/head'
import Image from 'next/image'
import { useState } from "react";
import Button from "../components/Button"
import Link from 'next/link'
import Title from '../components/Title'

export default function Paints(){
  return(
  <>
      <Head>
        <title>Download</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen flex justify-center items-center'>
        <div className='text-center relative'>
          <Title text="VOICI LES OEUVRES INFECTÉES"/>

          <Image
            src="/../public/jour_des_mort.png"
            alt="Image jour de morts"
            width={300}
            height={300}
            className="m-auto mt-10"
          />
          <Image
            src="/../public/waterloo_jaune.png"
            alt="Picture of a file"
            width={300}
            height={300}
            className="m-auto mt-10"
          />
          <Link href="/game1"><Button text="ouvrir>"/></Link>
        </div>

      </main>
    </>
  )
}
