
// This page is the home page
import Head from 'next/head'
import Image from 'next/image'
import { useState } from "react";
import Button from "../components/Button"
import Link from 'next/link'
import Title from '../components/Title'

export default function Paints(){
  return(
  <>
      <Head>
        <title>Download</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen flex justify-center items-center'>
        <div className='text-center relative h-4/6'>
          <Title text="VOICI LES OEUVRES INFECTÉES"/>

          <img className='w-[300px] h-auto' src="jour_des_mort.png" alt="" />
          <img className='w-[300px] h-auto' src="waterloo_jaune.png" alt="" />
          
          <Link className='text-primary 'href="/game1"><Button text="COMMENCER LE JEU ->"/></Link>
        </div>

      </main>
    </>
  )
}
