
// This page is the home page
import Head from 'next/head';
import Link from 'next/link';
import styles from '@/styles/Home.module.css';
import MessageBox from '@/components/MessageBox';
import { useState } from "react";
import Container from '@/components/Container';
import Button from "../components/Button";
import Title from '@/components/Title';
import Text from '@/components/Text';
import Intro from '@/components/Intro';
import TypeIt from 'typeit-react';


export default function Score() {

  <Head>
  <title>Game 1</title>
  <meta name="description" content="Generated by create next app" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="icon" href="/favicon.ico" />
  </Head>
      return (

        <Container>
        <Intro>
        <Title text="statistiques"/>
        <TypeIt className='text-primary' options={{
            strings: ["Les visiteurs passent en moyenne seulement 30 secondes devant un tableau."],
            speed: 10,
            waitUntilVisible: true,
          }}>
        </TypeIt>
        <div className='text-primary flex flex-col w-full items-center gap-y-4'>
        <img className='w-4/12 mx-auto' src="/d-teye.png" alt="d-teye image" />

        </div>
        <MessageBox>
        <TypeIt options={{
        strings: ["Les différences que j’ai dissimulées n’étaient qu’un prétexte pour vous faire apprécier les détails que le peintre a imaginés..."],
        speed: 10,
        waitUntilVisible: true,
        startDelay: 3000,
      }}className ="text-primary">
    </TypeIt>
        </MessageBox>
        <div className='w-full flex justify-center'>
        <Link href="/conclusion"><Button text="suivant"/></Link>

        </div>
        </Intro>
        </Container>
        )
      }

