
// This page is the home page
import Head from 'next/head'
import Container from "@/components/Container"
import TypeIt from "typeit-react";

export default function Home() {

  return (

    <>
      <Head>
        <title>D-TEYE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full">
      <TypeIt options={{
          strings: ["Bonjour. Je suis D-tEye: le virus informatique qui sévit pendant cette bacchanight... I"],
          speed: 10,
          waitUntilVisible: true,
        }}className ="text-primary">
      </TypeIt>
    </main>

    </>
  )
}
